/**
 * The real first-person arms, posed from CS2's own viewmodel animations.
 *
 * Two findings from the local install shape all of this.
 *
 * The agent model already contains `firstperson_default_gloves_arms` and
 * `firstperson_sleeves` on the *same skeleton* as the viewmodel poses, so the
 * arms and the poses fit each other exactly and no retargeting is involved.
 *
 * Every one of CS2's 628 viewmodel animations is a **single keyframe**. The
 * motion is generated by Valve's runtime animation graph, which is not in the
 * VPK. So `idle`, `shoot1`, `reload` and `draw` are static poses, and the motion
 * between them is interpolated here. That is why the poses are read out as plain
 * bone transforms and blended directly rather than being run through an
 * `AnimationMixer`: a zero-length clip is not something the mixer handles well,
 * and blending by hand is what a pose library needs anyway.
 *
 * The gun is gripped on `wpn` for pistols (the idle pose wraps the fingers
 * there) and on `hand_R` for rifles. Identity-parenting on `wpn` stands a
 * pistol on the forearms because that bone's +Z is up — the weapon bone
 * has to line up with it instead. Viewmodel clips leave the torso in bind
 * pose off to the side and stretch `arm_upper` from that clavicle into
 * camera space — those shoulder verts sit *behind* the lens. Placement
 * must not pull them forward, or the Preview fills with a sleeve instead
 * of a Deagle.
 */

import * as THREE from "three";
import { applyAgentMaterials } from "./assetMaterials";
import { FALLBACK_AGENT } from "./assetSpec";
import {
  bundleAgentPath,
  collectBones,
  findClip,
  instantiate,
  loadAsset,
  METRES_TO_INCHES,
  type AssetBundle,
} from "./gameAssets";
import { attachViewmodelWeapon, disposeWeaponModel, makeWeaponModel, updateWeaponModel, type WeaponModel } from "./weaponModels";
import { captureViewmodelRest } from "./viewmodel";
import type { WeaponInfo } from "./weaponTable";

/** First-person meshes inside the agent model. */
export const ARMS_MESHES = ["firstperson_default_gloves_arms", "firstperson_sleeves"];
/** The third-person body, hidden in the first-person view. */
export const BODY_MESH = "thirdperson_body";
/**
 * Zero-area placeholder meshes the exporter emits alongside the real ones, e.g.
 * `animation\skeletons\weapons\ak47\vnm_skel.empty_mesh_reference`. Eight
 * vertices each, but they still draw.
 */
export const PLACEHOLDER_MESH = "empty_mesh_reference";

/** Idle pose already sits about this far in front of the lens, in inches. */
const ARMS_DEPTH = 12;
/**
 * Shoulder/sleeve verts from the stretched clavicle chain sit at z ≥ 0.
 * Anything closer than this is that stretch, not the held gun.
 */
const CLUSTER_NEAR = -4;

export type BonePose = {
  position?: THREE.Vector3;
  quaternion?: THREE.Quaternion;
  scale?: THREE.Vector3;
};

/** Bone name to local transform. */
export type Pose = Map<string, BonePose>;

/**
 * Read a clip out as a pose.
 *
 * Sampling is nearest-earlier rather than interpolated, which is exact for the
 * single-keyframe viewmodel poses this is used on.
 */
export function extractPose(clip: THREE.AnimationClip, time = 0): Pose {
  const pose: Pose = new Map();
  for (const track of clip.tracks) {
    const parsed = THREE.PropertyBinding.parseTrackName(track.name);
    const bone = parsed.nodeName;
    const property = parsed.propertyName;
    if (!bone || !property) continue;

    const times = track.times;
    let index = 0;
    for (let i = 0; i < times.length; i++) {
      if (times[i] <= time) index = i;
      else break;
    }

    const values = track.values as ArrayLike<number>;
    const entry = pose.get(bone) ?? {};
    if (property === "position") {
      const o = index * 3;
      entry.position = new THREE.Vector3(values[o], values[o + 1], values[o + 2]);
    } else if (property === "quaternion") {
      const o = index * 4;
      entry.quaternion = new THREE.Quaternion(values[o], values[o + 1], values[o + 2], values[o + 3]);
    } else if (property === "scale") {
      const o = index * 3;
      entry.scale = new THREE.Vector3(values[o], values[o + 1], values[o + 2]);
    } else {
      continue;
    }
    pose.set(bone, entry);
  }
  return pose;
}

export function poseBoneNames(pose: Pose): string[] {
  return [...pose.keys()];
}

export { collectBones } from "./gameAssets";

/**
 * Blend `base` toward `target` by `t`, writing straight onto the bones.
 *
 * Bones only one pose knows about are still applied, so a pose that touches
 * fewer bones degrades to "leave that joint alone" rather than snapping it.
 */
export function applyBlendedPose(
  bones: Map<string, THREE.Object3D>,
  base: Pose,
  target: Pose | null,
  t: number,
) {
  const mix = target && t > 0 ? Math.min(1, t) : 0;
  for (const [name, from] of base) {
    const bone = bones.get(name);
    if (!bone) continue;
    const to = mix > 0 ? target?.get(name) : undefined;
    if (from.position) {
      bone.position.copy(from.position);
      if (to?.position) bone.position.lerp(to.position, mix);
    }
    if (from.quaternion) {
      bone.quaternion.copy(from.quaternion);
      if (to?.quaternion) bone.quaternion.slerp(to.quaternion, mix);
    }
    if (from.scale) {
      bone.scale.copy(from.scale);
      if (to?.scale) bone.scale.lerp(to.scale, mix);
    }
  }
  // A joint the target poses but the base does not would otherwise never move.
  if (mix > 0 && target) {
    for (const [name, to] of target) {
      if (base.has(name)) continue;
      const bone = bones.get(name);
      if (!bone) continue;
      if (to.position) bone.position.lerp(to.position, mix);
      if (to.quaternion) bone.quaternion.slerp(to.quaternion, mix);
      if (to.scale) bone.scale.lerp(to.scale, mix);
    }
  }
}

export type ArmsViewmodel = {
  /** Add to the viewmodel scene. Inches. */
  root: THREE.Group;
  model: THREE.Group;
  bones: Map<string, THREE.Object3D>;
  /** Weapon attach bone. The gun hangs off this. */
  wpnBone: THREE.Object3D | null;
  headBone: THREE.Object3D | null;
  poses: { idle: Pose | null; shoot: Pose | null; reload: Pose | null; draw: Pose | null };
  weapon: WeaponModel | null;
  info: WeaponInfo;
  bobPhase: number;
  swayYaw: number;
  swayPitch: number;
};

/**
 * Hide meshes whose name contains `needle`.
 *
 * Substring, not suffix: the exporter names meshes
 * `agents\models\ctm_sas\ctm_sas.vmdl_c.thirdperson_body` and then splits a
 * multi-primitive mesh into `..._1` through `..._4`, so a suffix match leaves the
 * whole third-person body visible in the first-person view — a full character
 * standing in front of the camera.
 */
export function hideMesh(root: THREE.Object3D, needle: string) {
  root.traverse((child) => {
    const mesh = child as THREE.Mesh;
    if (mesh.isMesh && mesh.name.includes(needle)) mesh.visible = false;
  });
}

export async function makeArmsViewmodel(
  bundle: AssetBundle | null,
  agent: string,
  info: WeaponInfo,
  team: string,
  skinKey = "",
): Promise<ArmsViewmodel | null> {
  const path = bundleAgentPath(bundle, agent);
  if (!path) return null;
  // Agent and gun paths are both known from the bundle; waiting on one then
  // the other just delays the first real viewmodel frame.
  const [loadedAgent, weapon] = await Promise.all([
    loadAsset(path),
    makeWeaponModel(bundle, info, { attached: true, skinKey }),
  ]);
  let loaded = loadedAgent;
  if (loaded && !findClip(loaded.animations, info.poses.idle) && agent !== FALLBACK_AGENT) {
    const fallback = await loadAsset(bundleAgentPath(bundle, FALLBACK_AGENT));
    if (fallback && findClip(fallback.animations, info.poses.idle)) loaded = fallback;
  }
  if (!loaded) {
    disposeWeaponModel(weapon);
    return null;
  }

  // Viewmodel poses are authored with +Z forward. Preview's camera looks -Z,
  // so the same 180° yaw the weapons use is what puts the hands in front of
  // the lens instead of behind it.
  const { root, model, animations } = instantiate(loaded, { flipForward: true });
  root.name = `arms:${agent}`;
  applyAgentMaterials(model, team);
  hideMesh(model, BODY_MESH);
  hideMesh(model, PLACEHOLDER_MESH);
  // Sleeves are skinned through the bind-pose clavicles 4 ft off to the side,
  // so they draw as a tube through the lens. Hands + gun are the real viewmodel.
  hideMesh(model, "firstperson_sleeves");

  const bones = collectBones(model);
  const poses = {
    idle: poseFrom(animations, info.poses.idle),
    shoot: poseFrom(animations, info.poses.shoot),
    reload: poseFrom(animations, info.poses.reload),
    draw: poseFrom(animations, info.poses.draw),
  };
  if (!poses.idle) {
    disposeWeaponModel(weapon);
    return null;
  }

  const vm: ArmsViewmodel = {
    root,
    model,
    bones,
    wpnBone: bones.get("wpn") ?? bones.get("wpnPivot") ?? null,
    headBone: bones.get("head_0") ?? null,
    poses,
    weapon: null,
    info,
    bobPhase: 0,
    swayYaw: Number.NaN,
    swayPitch: Number.NaN,
  };

  applyBlendedPose(bones, poses.idle, null, 0);
  model.updateMatrixWorld(true);

  // Pistols, knives and nades: fingers wrap `wpn`. Rifles: the palm is the grip.
  const wrapWpn =
    info.kind === "pistol" ||
    info.kind === "taser" ||
    info.kind === "knife" ||
    info.kind === "nade" ||
    info.kind === "c4";
  const grip = wrapWpn ? (vm.wpnBone ?? bones.get("hand_R")) : (bones.get("hand_R") ?? vm.wpnBone);
  if (weapon && grip) {
    attachViewmodelWeapon(weapon, grip);
    vm.weapon = weapon;
  } else if (weapon) {
    root.add(weapon.root);
    vm.weapon = weapon;
  }

  return vm;
}

function poseFrom(animations: THREE.AnimationClip[], name: string | null): Pose | null {
  const clip = findClip(animations, name);
  return clip ? extractPose(clip) : null;
}

export type ArmsMotion = {
  /** Seconds since the last shot, or null. */
  shotAge: number | null;
  /** Seconds since the last nade throw, or null. */
  throwAge?: number | null;
  /** 0..1 through a reload, or null. */
  reload: number | null;
  /** Seconds since the weapon was drawn, or null. */
  drawAge: number | null;
  speed?: number;
  walking?: boolean;
  dt?: number;
  yaw?: number;
  pitch?: number;
};

/** How long the hands take to snap back from the shoot pose, in seconds. */
const SHOOT_RETURN = 0.11;
/** Overhand throw is a held pose, not a 0.11s recoil flick. */
const THROW_SETTLE = 0.55;
/** Held nade hides once the projectile is in flight. */
const NADE_RELEASE = 0.12;
/** How long the draw pose takes to settle into idle. */
const DRAW_SETTLE = 0.4;

/**
 * Pose the hands for this tick and cycle the weapon's own moving parts.
 *
 * Priority is reload, then throw, then draw, then recoil: a nade pull-out must
 * not eat the overhand, and a reload is more specific than either.
 */
export function updateArmsViewmodel(vm: ArmsViewmodel, motion: ArmsMotion) {
  const { poses, bones } = vm;
  if (!poses.idle) return;

  let target: Pose | null = null;
  let weight = 0;

  const throwAge = motion.throwAge ?? null;

  if (poses.reload && motion.reload !== null && motion.reload >= 0 && motion.reload < 1) {
    target = poses.reload;
    // Ease in and out so the hands do not jump into and out of the reload.
    weight = Math.sin(Math.min(1, motion.reload) * Math.PI);
    weight = Math.min(1, weight * 2.2);
  } else if (poses.shoot && throwAge !== null && throwAge >= 0 && throwAge < THROW_SETTLE) {
    target = poses.shoot;
    weight = throwAge < 0.18 ? 1 : 1 - (throwAge - 0.18) / (THROW_SETTLE - 0.18);
  } else if (poses.draw && motion.drawAge !== null && motion.drawAge < DRAW_SETTLE) {
    target = poses.draw;
    weight = 1 - motion.drawAge / DRAW_SETTLE;
  } else if (poses.shoot && motion.shotAge !== null && motion.shotAge < SHOOT_RETURN) {
    target = poses.shoot;
    // Snap to the shoot pose and ease back, which is how recoil actually reads.
    weight = 1 - motion.shotAge / SHOOT_RETURN;
  }

  applyBlendedPose(bones, poses.idle, target, weight);

  if (vm.weapon) {
    updateWeaponModel(vm.weapon, { shotAge: motion.shotAge, reload: motion.reload });
    if (vm.info.kind === "nade") {
      const released = throwAge !== null && throwAge >= NADE_RELEASE;
      const drewAfter =
        motion.drawAge !== null && throwAge !== null && motion.drawAge < throwAge;
      vm.weapon.root.visible = !released || drewAfter;
    } else {
      vm.weapon.root.visible = true;
    }
  }

  const restX = vm.root.userData.restX;
  const restY = vm.root.userData.restY;
  const restZ = vm.root.userData.restZ;
  if (typeof restX !== "number" || typeof restY !== "number") return;

  const speed = motion.speed ?? 0;
  const step = Math.max(0, Math.min(0.25, motion.dt ?? 0));
  vm.bobPhase += speed * step * 0.045;
  const run = Math.max(0, Math.min(1, speed / 250));
  const amp = run * 0.38 * (motion.walking ? 0.45 : 1);
  const recoil = motion.shotAge !== null && motion.shotAge < SHOOT_RETURN ? 1 - motion.shotAge / SHOOT_RETURN : 0;

  const yaw = motion.yaw ?? 0;
  const pitch = motion.pitch ?? 0;
  if (!Number.isFinite(vm.swayYaw)) {
    vm.swayYaw = yaw;
    vm.swayPitch = pitch;
  }
  const follow = Math.min(1, step * 9);
  const dYaw = ((yaw - vm.swayYaw + 540) % 360) - 180;
  vm.swayYaw += dYaw * follow;
  vm.swayPitch += (pitch - vm.swayPitch) * follow;
  const lagYaw = THREE.MathUtils.clamp(dYaw, -12, 12);

  vm.root.position.x = restX + Math.sin(vm.bobPhase / 2) * amp * 0.5 + lagYaw * 0.012;
  vm.root.position.y = restY + Math.sin(vm.bobPhase) * amp - recoil * 0.22;
  if (typeof restZ === "number") vm.root.position.z = restZ + recoil * 0.35;
}

/** Bounds of the grip cluster only — not the sleeves running back into the camera. */
export function gripBounds(vm: ArmsViewmodel): THREE.Box3 {
  vm.root.updateMatrixWorld(true);
  const box = new THREE.Box3();
  const scratch = new THREE.Vector3();
  for (const name of ["hand_R", "hand_L", "wpn", "wpnPivot"]) {
    const bone = vm.bones.get(name);
    if (bone) box.expandByPoint(bone.getWorldPosition(scratch));
  }
  if (vm.weapon) box.expandByPoint(vm.weapon.muzzle.getWorldPosition(scratch));
  return box;
}

/**
 * Geometry of the held gun and hands, ignoring the clavicle-stretch sleeves
 * that run through and behind the lens.
 */
export function firstPersonBounds(vm: ArmsViewmodel, step = 12): THREE.Box3 {
  vm.root.updateMatrixWorld(true);
  const box = new THREE.Box3();
  const point = new THREE.Vector3();
  vm.root.traverse((child) => {
    const mesh = child as THREE.SkinnedMesh;
    if (!mesh.visible || !mesh.isMesh || !mesh.geometry) return;
    const pos = mesh.geometry.getAttribute("position") as THREE.BufferAttribute | undefined;
    if (!pos) return;
    const skinned = mesh.isSkinnedMesh === true;
    if (skinned) mesh.skeleton.update();
    for (let i = 0; i < pos.count; i += Math.max(1, step)) {
      if (skinned) mesh.applyBoneTransform(i, point.fromBufferAttribute(pos, i));
      else point.fromBufferAttribute(pos, i);
      point.applyMatrix4(mesh.matrixWorld);
      if (point.z > CLUSTER_NEAR || point.z < -80) continue;
      box.expandByPoint(point);
    }
  });
  return box.isEmpty() ? gripBounds(vm) : box;
}

/**
 * Keep the authored camera-space pose.
 *
 * `idle_deagle` already puts the hands ~12" in front of the origin, lower
 * right, after the +Z → −Z yaw. Recentering on first-person mesh bounds
 * dragged the behind-lens shoulders into the frustum and filled Preview
 * with a sleeve. A short pane may clip the magazine — CS2 does the same.
 */
export function placeArmsViewmodel(vm: ArmsViewmodel, camera: THREE.PerspectiveCamera): boolean {
  vm.root.position.set(0, 0, 0);
  vm.root.rotation.set(0, Math.PI, 0);
  vm.root.scale.setScalar(METRES_TO_INCHES);
  vm.root.updateMatrixWorld(true);

  const hand = vm.bones.get("hand_R");
  if (!hand) return false;
  const at = hand.getWorldPosition(new THREE.Vector3());
  if (at.z > -2 || at.length() > 80) return false;

  const halfH = Math.tan(THREE.MathUtils.degToRad(camera.fov / 2)) * ARMS_DEPTH;
  const halfW = halfH * Math.max(camera.aspect, 0.0001);
  const box = firstPersonBounds(vm);
  // Nade idle is authored on the lens centre. Do not pull it left to fit the
  // can in frame — CS parks grenades lower-right, partly off-screen.
  if (!box.isEmpty() && vm.info.kind !== "nade") {
    const floor = -halfH * 0.95;
    if (at.y < floor) vm.root.position.y += floor - at.y;
    const right = halfW * 0.92;
    if (box.max.x > right) vm.root.position.x -= box.max.x - right;
  }
  vm.root.updateMatrixWorld(true);

  // Rifles sit on the crosshair if we only lift a low hand. Drop them so the
  // sights live under the reticle the way CS2 does.
  if (vm.info.kind === "rifle" || vm.info.kind === "sniper") {
    vm.root.position.y -= 8;
    vm.root.position.z -= 3;
    vm.root.updateMatrixWorld(true);
  }
  if (vm.info.kind === "nade") {
    vm.root.position.x += 11;
    vm.root.position.y -= 12;
    vm.root.position.z -= 6;
    vm.root.updateMatrixWorld(true);
  }

  vm.root.userData.restX = vm.root.position.x;
  vm.root.userData.restY = vm.root.position.y;
  vm.root.userData.restZ = vm.root.position.z;
  captureViewmodelRest(vm.root);
  return true;
}

/**
 * True when the posed right hand is in front of the camera and within reach.
 * Call after `placeArmsViewmodel` — before fitting, the unscaled metres fail this.
 */
export function frameArmsInView(vm: ArmsViewmodel): boolean {
  vm.root.updateMatrixWorld(true);
  const hand = vm.bones.get("hand_R");
  if (!hand) return false;
  const at = hand.getWorldPosition(new THREE.Vector3());
  return at.z < -2 && at.y < 8 && at.length() < 80;
}

export function disposeArmsViewmodel(vm: ArmsViewmodel | null) {
  if (!vm) return;
  vm.weapon?.mixer?.stopAllAction();
  vm.root.removeFromParent();
}
